"""create caffeine_intake table

Revision ID: 0453f86e9766
Revises: 
Create Date: 2026-03-02 14:12:11.922688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0453f86e9766'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caffeine_intake',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('intake_datetime', sa.DateTime(), nullable=False),
    sa.Column('amount_mg', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint('amount_mg > 0'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('caffeine_intake', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_caffeine_intake_intake_datetime'), ['intake_datetime'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('caffeine_intake', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_caffeine_intake_intake_datetime'))

    op.drop_table('caffeine_intake')
    # ### end Alembic commands ###
